#!/usr/bin/bash

# executes same behaviour as below but with support for images
#
# cliphist list | wofi --dmenu | cliphist decode
#
# produces thumbnails and stores them in XDG_CACHE_HOME
# note: does NOT put in clipboard, call wl-copy yourself!

# set up thumbnail directory
thumb_dir="/tmp/cliphist"
mkdir -p "$thumb_dir"

cliphist_list="$(cliphist list)"

# Display image
read -r -d '' prog <<EOF
/^[0-9]+\s<meta http-equiv=/ { next }
match(\$0, /^([0-9]+)\s(\[\[\s)?binary.*(jpg|jpeg|png|bmp)/, grp) {
    image = grp[1]"."grp[3]
    system("[ -f $thumb_dir/"image" ] || echo " grp[1] "\\\\\t | cliphist decode > $thumb_dir/"image )
    print "img:$thumb_dir/"image
    next
}
1
EOF

choice=$(gawk <<< $cliphist_list "$prog" | wofi -I --dmenu -Dimage_size=100 -Dynamic_lines=true -p "Clipboard" --color "$HOME/.config/wofi/colors")

# stop execution if nothing selected in wofi menu
[ -z "$choice" ] && exit 1

if [ "${choice::4}" = "img:" ]; then
    thumb_file="${choice:4}"
    clip_id="${thumb_file##*/}"
    clip_id="${clip_id%.*}\t"
else
    clip_id="${choice}"
fi

printf "$clip_id" | cliphist decode | wl-copy
