#!/usr/bin/bash

image_dir="$HOME/.systemui/wallpapers/"
thumb_dir="/tmp/wofi_thumbs"
mkdir -p "$thumb_dir"

while read -r img; do
  thumb_name=$(basename "$img")
  thumb_path="$thumb_dir/$thumb_name"
  [ -f "$thumb_path" ] || convert "$img" -thumbnail 200x200 "$thumb_path"
  echo "img:$thumb_path"
done < <(find "$image_dir" -type f \( -iname "*.jpg" -o -iname "*.jpeg" -o -iname "*.png" -o -iname "*.bmp" \)) \
  | wofi -I --dmenu -Dimage_size=100 -Dynamic_lines=true -p "Select Image" --color "$HOME/.config/wofi/colors" \
  | {
      read -r selected
      if [[ "$selected" == img:* ]]; then
        image_path="${selected#img:/tmp/wofi_thumbs/}"
        echo -e "Light Mode\nDark Mode" \
          | wofi --dmenu -I --color "$HOME/.config/wofi/colors" -p "Select theme" \
          | while read -r mode; do
              case "$mode" in
                "Light Mode")
                  swww img "$image_dir/$image_path" --transition-type=wave --transition-pos=top-right
                  ignis run-python "from scripts import colors;colors.ColorManager().update('$image_dir/$image_path',1)"
                  ;;
                "Dark Mode")
                  swww img "$image_dir/$image_path" --transition-type=wave --transition-pos=top-right
                  ignis run-python "from scripts import colors;colors.ColorManager().update('$image_dir/$image_path',0)"
                  ;;
                *)
                  echo "No theme selection."
                  ;;
              esac
            done
      else
        echo "Error: Invalid selection."
      fi
    }
